import type { BGGSearchResult } from './types';

export const POPULAR_GAMES: BGGSearchResult[] = [
  {
    id: 13,
    name: 'Catan',
    year_published: 1995,
    image: 'https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__original/img/xV7oisd3RQ8R-k18cdWAYthHXsA=/0x0/filters:format(jpeg)/pic2419375.jpg',
    thumbnail: 'https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__thumb/img/8a9HeqFydO7Uun_le9bXWPnidcA=/fit-in/200x150/filters:strip_icc()/pic2419375.jpg',
    description: 'Collect and trade resources to build up the island of Catan in this modern classic.',
    min_players: 3,
    max_players: 4,
    playing_time: 90,
    average_weight: 2.32,
  },
  {
    id: 174430,
    name: 'Gloomhaven',
    year_published: 2017,
    image: 'https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__original/img/7d-lj5Gd1e8PFnD97LYFah2c45M=/0x0/filters:format(jpeg)/pic2437871.jpg',
    thumbnail: 'https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__thumb/img/veqFeP4d_3zNpEVMuhyGOERG1s0=/fit-in/200x150/filters:strip_icc()/pic2437871.jpg',
    description: 'Vanquish monsters with strategic cardplay in a persistent campaign.',
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    average_weight: 3.86,
  },
  {
    id: 167791,
    name: 'Terraforming Mars',
    year_published: 2016,
    image: null,
    thumbnail: null,
    description: 'Compete with rival corporations to terraform Mars.',
    min_players: 1,
    max_players: 5,
    playing_time: 120,
    average_weight: 3.24,
  },
  {
    id: 266192,
    name: 'Wingspan',
    year_published: 2019,
    image: 'https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__original/img/cI782Zis9cT66j2MjSHKJGnFPNw=/0x0/filters:format(jpeg)/pic4458123.jpg',
    thumbnail: 'https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__thumb/img/Z-BIimnfJuXwMl-TY0dLEb6E3Mw=/fit-in/200x150/filters:strip_icc()/pic4458123.jpg',
    description: 'Attract a beautiful and diverse collection of birds to your wildlife preserve.',
    min_players: 1,
    max_players: 5,
    playing_time: 70,
    average_weight: 2.44,
  },
  {
    id: 312484,
    name: 'Lost Ruins of Arnak',
    year_published: 2020,
    image: null,
    thumbnail: null,
    description: 'Explore an uninhabited island, find artifacts, and face guardians.',
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    average_weight: 2.92,
  },
  {
    id: 224517,
    name: 'Brass: Birmingham',
    year_published: 2018,
    image: 'https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__original/img/FpyxH41Y6_ROoePAilPNEhXnzO8=/0x0/filters:format(jpeg)/pic3490053.jpg',
    thumbnail: 'https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__thumb/img/C5BQZF2KLXWRVN0fkLcRAlEhO00=/fit-in/200x150/filters:strip_icc()/pic3490053.jpg',
    description: 'Build networks, grow industries, and navigate the industrial revolution in Birmingham.',
    min_players: 2,
    max_players: 4,
    playing_time: 120,
    average_weight: 3.91,
  },
  {
    id: 342942,
    name: 'Ark Nova',
    year_published: 2021,
    image: 'https://cf.geekdo-images.com/SoU8p28Sk1s8MSvoM4N8pQ__original/img/g4S18szTdrXCdIwVKzMKrZrYAcM=/0x0/filters:format(jpeg)/pic6293412.jpg',
    thumbnail: 'https://cf.geekdo-images.com/SoU8p28Sk1s8MSvoM4N8pQ__thumb/img/BLT6OIPU-VT0VKjyvLqoFnJiVEw=/fit-in/200x150/filters:strip_icc()/pic6293412.jpg',
    description: 'Plan and build a modern, scientifically managed zoo to support conservation.',
    min_players: 1,
    max_players: 4,
    playing_time: 150,
    average_weight: 3.71,
  },
  {
    id: 316554,
    name: 'Dune: Imperium',
    year_published: 2020,
    image: 'https://cf.geekdo-images.com/PhjygpWSo-0labGrPBMyyg__original/img/mZzaBAEEJpMlHWWmC0R6Su0OibQ=/0x0/filters:format(jpeg)/pic5666597.jpg',
    thumbnail: 'https://cf.geekdo-images.com/PhjygpWSo-0labGrPBMyyg__thumb/img/M55LPdGPnJliPsUJbFGH1gVHFQc=/fit-in/200x150/filters:strip_icc()/pic5666597.jpg',
    description: 'Influence, intrigue, and combat in the universe of Dune.',
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    average_weight: 3.01,
  },
  {
    id: 178900,
    name: 'Codenames',
    year_published: 2015,
    image: null,
    thumbnail: null,
    description: 'Give one-word clues to help your teammates identify secret agents.',
    min_players: 2,
    max_players: 8,
    playing_time: 15,
    average_weight: 1.28,
  },
  {
    id: 169786,
    name: 'Scythe',
    year_published: 2016,
    image: null,
    thumbnail: null,
    description: 'Five factions vie for dominance in a war-torn, mech-filled, diesel-punk 1920s Europe.',
    min_players: 1,
    max_players: 5,
    playing_time: 115,
    average_weight: 3.42,
  },
  {
    id: 68448,
    name: '7 Wonders',
    year_published: 2010,
    image: null,
    thumbnail: null,
    description: 'Draft cards to develop your ancient civilization and build its Wonder of the World.',
    min_players: 2,
    max_players: 7,
    playing_time: 30,
    average_weight: 2.33,
  },
  {
    id: 36218,
    name: 'Dominion',
    year_published: 2008,
    image: null,
    thumbnail: null,
    description: 'Build a deck of treasure, action, and victory cards to outduel your opponents.',
    min_players: 2,
    max_players: 4,
    playing_time: 30,
    average_weight: 2.36,
  },
  {
    id: 233078,
    name: 'Inis',
    year_published: 2016,
    image: 'https://cf.geekdo-images.com/PhjygpWSo-0labGrPBMyyg__original/img/mZzaBAEEJpMlHWWmC0R6Su0OibQ=/0x0/filters:format(jpeg)/pic5666597.jpg',
    thumbnail: null,
    description: 'Draft cards and control territories to become King of the Island.',
    min_players: 2,
    max_players: 4,
    playing_time: 90,
    average_weight: 3.07,
  },
  {
    id: 124361,
    name: 'Concordia',
    year_published: 2013,
    image: null,
    thumbnail: null,
    description: 'Develop your trade network across the Roman Empire using hand management.',
    min_players: 2,
    max_players: 5,
    playing_time: 100,
    average_weight: 3.04,
  },
  {
    id: 187645,
    name: 'Star Wars: Rebellion',
    year_published: 2016,
    image: 'https://cf.geekdo-images.com/7SrPNGBKg9IIsP4UQpOi8g__original/img/GKueTbkCk2Ramf6ai8mDj-BP6cI=/0x0/filters:format(jpeg)/pic4325841.jpg',
    thumbnail: 'https://cf.geekdo-images.com/7SrPNGBKg9IIsP4UQpOi8g__thumb/img/gk0qgC3PogsVuxZl4BPnpUZjPvg=/fit-in/200x150/filters:strip_icc()/pic4325841.jpg',
    description: 'Experience the Galactic Civil War like never before.',
    min_players: 2,
    max_players: 4,
    playing_time: 240,
    average_weight: 3.66,
  },
  {
    id: 291457,
    name: 'Gloomhaven: Jaws of the Lion',
    year_published: 2020,
    image: null,
    thumbnail: null,
    description: 'A standalone Gloomhaven game with a streamlined learning experience.',
    min_players: 1,
    max_players: 4,
    playing_time: 120,
    average_weight: 3.57,
  },
];
